services:

  postgres:
    image: postgres:16
    container_name: supplychain-postgres
    restart: unless-stopped

    env_file:
      - ../.env

    # The environment variables are extracted from the .env file in Azure vm instance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: SupplyChainDatabase

    # As we need to preserve the same data so persistance is required, and volumes are used to make postgres data persistant.
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d SupplyChainDatabase" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend

    container_name: supplychain-backend
    restart: unless-stopped

    env_file:
      - ../.env

    # The environment variables are extracted from the .env file in Azure vm instance
    environment:
      DB_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/SupplyChainDatabase
      MODEL_DB_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/MLflowDatabase
      GROQ_API_KEY: ${GROQ_API_KEY}

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: supplychain-mlflow
    restart: unless-stopped

    command: >
      mlflow server --backend-store-uri postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/MLflowDatabase --default-artifact-root /mlartifacts --host 0.0.0.0 --port 5000

    volumes:
      - mlflow_artifacts:/mlartifacts

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "5000:5000"

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend

    container_name: supplychain-frontend
    restart: unless-stopped

    environment:
      BACKEND_URL: http://backend:8000

    depends_on:
      - backend

    ports:
      - "8501:8501"

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: supplychain-litellm
    restart: unless-stopped

    env_file:
      - ../.env

    command: >
      --config /app/config.yaml --port 4000 --host 0.0.0.0

    volumes:
      - ./litellm/config.yaml:/app/config.yaml:ro

    expose:
      - "4000"

volumes:
  postgres_data:
  mlflow_artifacts:
