FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY backend ./backend
COPY docker/nemo_guardrails ./docker/nemo_guardrails
COPY configs ./configs
COPY ml_pipeline ./ml_pipeline
COPY utils ./utils

EXPOSE 8000

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]